"use client";

import { ArrowRight, FileJson2, FolderKanban, Network } from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";

import { Breadcrumb } from "@/components/layout/breadcrumb";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Markdown } from "@/features/agents/components/markdown";
import { useRunSource } from "@/features/centers/hooks/use-run-source";
import { useProjects } from "@/features/projects/hooks/use-projects";
import { buildMermaid, stepForAgent } from "@/features/workspace/lib/artifacts";
import { stepMarkdown } from "@/services/agents";
import { DiagramCanvas } from "./diagram-canvas";
import { Select } from "@/components/ui/select";
import type { AgentStep } from "@/services/agents";

interface DiagramDefinition {
  key: string;
  label: string;
  agentKey: string;
}

const DIAGRAMS: DiagramDefinition[] = [
  { key: "architecture", label: "System Architecture", agentKey: "solution_architect" },
  { key: "database", label: "Database", agentKey: "database_architect" },
  { key: "backend", label: "Backend", agentKey: "backend_engineer" },
  { key: "deployment", label: "Deployment", agentKey: "devops_engineer" },
];

/** Mermaid source for a diagram tab (null when the agent emitted no graph). */
function diagramSource(
  definition: DiagramDefinition,
  steps: AgentStep[] | undefined,
): string | null {
  const step = stepForAgent(steps, definition.agentKey);
  if (!step) {
    return null;
  }
  return buildMermaid(step);
}

export function ArchitecturePage({ initialProjectId }: { initialProjectId: string | null }) {
  const projectsQuery = useProjects({ page_size: 50 });
  const projects = useMemo(() => projectsQuery.data?.items ?? [], [projectsQuery.data]);

  const [projectId, setProjectId] = useState<string | undefined>(initialProjectId ?? undefined);
  const source = useRunSource(projectId);

  // If a project was passed via the URL and still exists, keep it. The guard
  // runs once the list is available; later list refreshes do not re-apply it.
  const appliedInitial = useRef(false);
  useEffect(() => {
    if (appliedInitial.current || !initialProjectId || projectsQuery.isLoading) {
      return;
    }
    appliedInitial.current = true;
    if (projects.some((project) => project.id === initialProjectId)) {
      setProjectId(initialProjectId);
    }
  }, [initialProjectId, projects, projectsQuery.isLoading]);

  return (
    <div className="space-y-6">
      <Breadcrumb
        items={[
          { label: "Dashboard", href: "/dashboard" },
          { label: "Architecture" },
        ]}
      />

      <header className="flex flex-wrap items-end justify-between gap-4">
        <div className="space-y-1.5">
          <h1 className="text-2xl font-semibold tracking-tight">Architecture Viewer</h1>
          <p className="text-sm text-muted-foreground">
            Pan, zoom, and export the system diagrams generated by the agent pipeline.
          </p>
        </div>
        <div className="w-full sm:w-72">
          <label
            htmlFor="architecture-project"
            className="mb-1.5 block text-xs font-medium text-muted-foreground"
          >
            Project
          </label>
          <Select
            id="architecture-project"
            value={projectId ?? ""}
            onChange={(event) => setProjectId(event.target.value || undefined)}
          >
            <option value="">Select a project</option>
            {projects.map((project) => (
              <option key={project.id} value={project.id}>
                {project.name}
              </option>
            ))}
          </Select>
        </div>
      </header>

      {!projectId ? (
        <EmptyState
          icon={<FolderKanban className="size-5" />}
          title="No project selected"
          description="Choose a project above to view the architecture its agent pipeline generated."
        />
      ) : source.isLoading ? (
        <div className="space-y-3">
          <Skeleton className="h-10 w-full" />
          <Skeleton className="h-[560px] w-full" />
        </div>
      ) : source.error ? (
        <ErrorState onRetry={source.refetch} />
      ) : source.empty || !source.steps ? (
        <EmptyState
          icon={<Network className="size-5" />}
          title="No completed pipeline yet"
          description="Run the agent pipeline for this project in the workspace first — the architecture diagram appears here when it completes."
          action={
            <Link href={`/workspace/${projectId}`}>
              <Button size="sm">
                Open workspace
                <ArrowRight aria-hidden="true" />
              </Button>
            </Link>
          }
        />
      ) : (
        <Tabs defaultValue="architecture">
          <TabsList aria-label="Diagrams">
            {DIAGRAMS.map((diagram) => (
              <TabsTrigger key={diagram.key} value={diagram.key}>
                {diagram.label}
              </TabsTrigger>
            ))}
            <TabsTrigger value="json">
              <FileJson2 aria-hidden="true" />
              Architecture JSON
            </TabsTrigger>
          </TabsList>

          {DIAGRAMS.map((diagram) => {
            const step = stepForAgent(source.steps, diagram.agentKey);
            return (
              <TabsContent key={diagram.key} value={diagram.key} className="mt-4 space-y-4">
                <DiagramCanvas source={diagramSource(diagram, source.steps)} label={diagram.label} />
                {step ? (
                  <Card>
                    <CardHeader>
                      <CardTitle className="text-sm">{diagram.label}</CardTitle>
                      <CardDescription>
                        Summary generated by the {step.agent.replace(/_/g, " ")} agent.
                      </CardDescription>
                    </CardHeader>
                    <CardContent>
                      <div className="max-w-3xl">
                        <Markdown content={stepMarkdown(step)} />
                      </div>
                    </CardContent>
                  </Card>
                ) : null}
              </TabsContent>
            );
          })}

          <TabsContent value="json" className="mt-4">
            <Card>
              <CardHeader>
                <CardTitle className="text-sm">Structured architecture data</CardTitle>
                <CardDescription>Raw JSON output of the pipeline agents.</CardDescription>
              </CardHeader>
              <CardContent>
                <pre className="max-h-[560px] overflow-auto rounded-md border border-border bg-muted/40 p-4 font-mono text-xs leading-relaxed">
                  {JSON.stringify(
                    Object.fromEntries(
                      DIAGRAMS.map((diagram) => {
                        const step = stepForAgent(source.steps, diagram.agentKey);
                        return [diagram.agentKey, step?.output ?? null];
                      }),
                    ),
                    null,
                    2,
                  )}
                </pre>
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      )}
    </div>
  );
}

function EmptyState({
  icon,
  title,
  description,
  action,
}: {
  icon: ReactNode;
  title: string;
  description: string;
  action?: ReactNode;
}) {
  return (
    <div className="flex min-h-[420px] flex-col items-center justify-center rounded-lg border border-dashed border-border bg-card/50 p-10 text-center">
      <div
        className="flex size-12 items-center justify-center rounded-lg border border-border bg-muted text-muted-foreground"
        aria-hidden="true"
      >
        {icon}
      </div>
      <h2 className="mt-5 text-lg font-semibold tracking-tight">{title}</h2>
      <p className="mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">{description}</p>
      {action ? <div className="mt-6">{action}</div> : null}
    </div>
  );
}

function ErrorState({ onRetry }: { onRetry: () => void }) {
  return (
    <div className="flex min-h-[420px] flex-col items-center justify-center rounded-lg border border-dashed border-border bg-card/50 p-10 text-center">
      <div
        className="flex size-12 items-center justify-center rounded-lg border border-border bg-muted text-muted-foreground"
        aria-hidden="true"
      >
        <Network className="size-5" />
      </div>
      <h2 className="mt-5 text-lg font-semibold tracking-tight">Unable to load the diagrams</h2>
      <p className="mt-2 max-w-md text-sm leading-relaxed text-muted-foreground">
        The pipeline data could not be fetched. Check the connection and retry.
      </p>
      <Button size="sm" variant="outline" className="mt-6" onClick={onRetry}>
        Retry
      </Button>
    </div>
  );
}
